name: Check

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install .

      - name: git credentials
        uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
      
      - name: execute py script
        run: |
          echo `pwd`
          python -m packaging
          git status
          if [ -z "$(git status --porcelain)" ]; then
            echo "Working directory clean"
          else
            echo "Changes detected"
            git commit -a -F commit_message.txt
            git push
            # Create release
            date=$(date '+%Y-%m-%d')
            gh create release -F commit_message.txt $date
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
