name: Slack Notification
on:
    workflow_dispatch:
    push:
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get message
        run: |
          {
          echo 'SLACK_MESSAGE<<EOF'
          cat environments/seamm.yml
          echo EOF
          } >> "$GITHUB_ENV"
          
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: 'github'
          slack-message: ${{ env.SLACK_MESSAGE }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

